# pylint: skip-file
"""Type stubs for the snekwest._bindings native extension module."""

from typing import Any, Optional, Tuple, Union

# Exception classes
class RequestException(Exception): ...

# Direct children of RequestException
class HTTPError(RequestException): ...
class ConnectionError(RequestException): ...
class URLRequired(RequestException): ...
class TooManyRedirects(RequestException): ...
class MissingSchema(RequestException): ...
class InvalidSchema(RequestException): ...
class InvalidURL(RequestException): ...
class InvalidHeader(RequestException): ...
class ChunkedEncodingError(RequestException): ...
class ContentDecodingError(RequestException): ...
class StreamConsumedError(RequestException): ...
class RetryError(RequestException): ...
class UnrewindableBodyError(RequestException): ...
class InvalidJSONError(RequestException): ...

# Timeout inherits from ConnectionError (matching python-requests hierarchy)
class Timeout(ConnectionError): ...

# Children of ConnectionError
class ProxyError(ConnectionError): ...
class SSLError(ConnectionError): ...

# Children of Timeout
class ConnectTimeout(Timeout): ...
class ReadTimeout(Timeout): ...

# Children of InvalidURL
class InvalidProxyURL(InvalidURL): ...

# Children of InvalidJSONError
class JSONDecodeError(InvalidJSONError): ...

# Warnings
class RequestsWarning(Warning): ...
class FileModeWarning(RequestsWarning): ...
class RequestsDependencyWarning(RequestsWarning): ...

class Response:
    """HTTP response returned by the Rust backend."""

    status: int
    url: str
    headers: dict[str, str]
    cookies: dict[str, str]
    reason: Optional[str]
    elapsed_ms: float
    history: list["Response"]
    is_redirect: bool
    method: str
    request_url: str
    request_headers: dict[str, str]

    def json(self) -> Any: ...
    def text(self) -> str: ...
    def content(self) -> bytes: ...

class Session:
    """HTTP session backed by a Rust reqwest client."""

    max_redirects: int
    default_headers: Optional[dict[str, str]]
    default_auth: Optional[Tuple[str, str]]
    default_params: Optional[dict[str, str]]

    def __new__(cls) -> "Session": ...
    def __init__(self) -> None: ...
    def make_request(
        self,
        method: str,
        url: str,
        *,
        params: Optional[dict[str, str]] = None,
        data: Optional[Union[dict[str, str], str, bytes]] = None,
        json: Optional[Any] = None,
        headers: Optional[dict[str, str]] = None,
        cookies: Optional[dict[str, str]] = None,
        files: Optional[dict[str, str]] = None,
        auth: Optional[Tuple[str, str]] = None,
        timeout: Optional[
            Union[float, Tuple[Optional[float], Optional[float]]]
        ] = None,
        allow_redirects: Optional[bool] = None,
        proxies: Optional[dict[str, str]] = None,
        stream: Optional[bool] = None,
        verify: Optional[bool] = None,
        cert: Optional[Union[str, Tuple[str, str]]] = None,
    ) -> Response: ...
    def close(self) -> None: ...
    def get_cookies(self) -> dict[str, str]: ...
    def set_cookies(self, cookies: dict[str, str]) -> None: ...
    def set_cookie(self, key: str, value: str) -> None: ...
    def remove_cookie(self, key: str) -> None: ...
