"""Exception classes for snekwest.

Re-exported from the native Rust extension module.
"""

# pylint: disable=no-name-in-module,redefined-builtin
from snekwest._bindings import (
    ChunkedEncodingError,
    ConnectionError,
    ConnectTimeout,
    ContentDecodingError,
    FileModeWarning,
    HTTPError,
    InvalidHeader,
    InvalidJSONError,
    InvalidProxyURL,
    InvalidSchema,
    InvalidURL,
    JSONDecodeError,
    MissingSchema,
    ProxyError,
    ReadTimeout,
    RequestException,
    RequestsDependencyWarning,
    RequestsWarning,
    RetryError,
    SSLError,
    StreamConsumedError,
    Timeout,
    TooManyRedirects,
    UnrewindableBodyError,
    URLRequired,
)

__all__ = [
    "RequestException",
    "HTTPError",
    "ConnectionError",
    "ProxyError",
    "SSLError",
    "Timeout",
    "ConnectTimeout",
    "ReadTimeout",
    "URLRequired",
    "TooManyRedirects",
    "MissingSchema",
    "InvalidSchema",
    "InvalidURL",
    "InvalidHeader",
    "InvalidProxyURL",
    "ChunkedEncodingError",
    "ContentDecodingError",
    "StreamConsumedError",
    "RetryError",
    "UnrewindableBodyError",
    "InvalidJSONError",
    "JSONDecodeError",
    "RequestsWarning",
    "FileModeWarning",
    "RequestsDependencyWarning",
]
